#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  MailForm:
    to:
      email: ''
      name: ''
    subjectPrefix: ''
