#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  MailForm:
    to:
      email: ''
      name: ''
    subjectPrefix: ''

  TYPO3CR:
    contentTypes:
      'TYPO3.MailForm:Plugin':
        superTypes: ['TYPO3.Phoenix.ContentTypes:Plugin']
        label: 'Mail Form'
        group: 'Plugins'
