#                                                                        #
# Settings                                                               #
#                                                                        #

MailForm:
  to:
    email: ''
    name: ''
  subjectPrefix: ''
